service: quarkus-on-lambda-redis

provider:
  name: aws
  runtime: provided
  stage: dev
  region: us-east-1
  endpointType: REGIONAL
  tracing:
    apiGateway: true
    lambda: true
    
package:
  artifact: target/bundle/function.zip

functions:
  hello:
    handler: function.sh
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    environment:
      REDIS_HOST: demo.uhm99s.0001.use1.cache.amazonaws.com
    vpc:
      securityGroupIds:
        - sg-e9d737a0
      subnetIds:
        - subnet-584fab3f
        - subnet-c169bf8b
        - subnet-867b76db

