service: quarkus-on-lambda-dynamodb 

provider:
  name: aws
  runtime: provided
  endpointType: REGIONAL
  stage: dev
  region: ap-northeast-1
  tracing:
    apiGateway: true
    lambda: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - arn:aws:dynamodb:ap-northeast-1:373534280245:table/Quotes

package:
  artifact: target/bundle/function.zip

functions:
  hello:
    handler: function.sh
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    layers:
      - {Ref: GraalvmSecurityLambdaLayer}

layers:
  GraalvmSecurity:
    path: lambda-layer 