# serverless.yml

service: nodejs-on-lambda

provider:
  name: aws
  runtime: nodejs10.x
  endpointType: REGIONAL
  stage: dev
  region: ap-northeast-1
  tracing:
    apiGateway: true
    lambda: true
    
functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
