# serverless.yml

service: nodejs-on-lambda

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-northeast-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
