  AWSTemplateFormatVersion: '2010-09-09'
  Transform: AWS::Serverless-2016-10-31
  Description: AWS Serverless Quarkus HTTP - com.amazonaws.serverless.sample::quarkus-sns-firehose-example
  Globals:
    Api:
      EndpointConfiguration: REGIONAL
      BinaryMediaTypes:
        - "*/*"

  Resources:
    QuarkusSnsFirehoseExampleFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
        Runtime: java8
        CodeUri: target/quarkus-sns-firehose-example-1.0-SNAPSHOT-runner.jar
        MemorySize: 128
        Timeout: 15
        Policies: AWSLambdaBasicExecutionRole