service: java-on-lambda-dynamodb

provider:
  name: aws
  runtime: java8
  endpointType: REGIONAL
  stage: dev
  region: ap-northeast-1
  tracing:
    apiGateway: true
    lambda: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - arn:aws:dynamodb:ap-northeast-1:373534280245:table/Quotes

package:
  artifact: target/hello-dev.jar

functions:
  hello:
    handler: com.serverless.Handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
