#!/bin/sh

set -euo pipefail

# Initialization - load function handler
EXEC=$LAMBDA_TASK_ROOT/$_HANDLER

echo $(pwd)
echo $(which aws-graal)

# Processing
while true
do
  HEADERS="$(mktemp)"
  # Get an event
  EVENT_DATA=$(curl -sS -LD "$HEADERS" -X GET "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next")

  echo $EVENT_DATA
  echo $EXEC

  REQUEST_ID=$(grep -Fi Lambda-Runtime-Aws-Request-Id "$HEADERS" | tr -d '[:space:]' | cut -d: -f2)

  echo $REQUEST_ID


  # Execute the handler function from the script
  #RESPONSE=`$EXEC $REQUEST_ID`
  RESPONSE=$(/var/task/aws-graal $EVENT_DATA)

  # Send the response
  curl -X POST "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/$REQUEST_ID/response"  -d "$RESPONSE"
done