service: java-on-lambda 

provider:
  name: aws
  runtime: java8
  endpointType: REGIONAL
  stage: dev
  region: us-east-1
  tracing:
    apiGateway: true
    lambda: true

package:
  artifact: target/hello-dev.jar

functions:
  hello:
    handler: com.serverless.Handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

