# serverless.yml

service: nodejs-on-lambda-redis

provider:
  name: aws
  runtime: nodejs10.x
  endpointType: REGIONAL
  stage: dev
  timeout: 10
  region: ap-northeast-1
  tracing:
    apiGateway: true
    lambda: true
    
functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    environment:
      REDIS_HOST: demo.j5hprq.0001.apne1.cache.amazonaws.com
    vpc:
      securityGroupIds:
        - sg-61dbd018
      subnetIds:
        - subnet-1716355e
        - subnet-2acaf602
        - subnet-a0a834fb